/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated.batches'
import { Route as AuthenticatedDevelopersRouteImport } from './routes/_authenticated.developers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthInviteRouteImport } from './routes/auth.invite'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated.templates.index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated.templates.$templateId'
import { Route as ApiV1TemplatesRouteImport } from './routes/api.v1.templates'
import { Route as ApiWebhooksResendRouteImport } from './routes/api.webhooks.resend'
import { Route as ApiV1DocumentsDocumentIdRouteImport } from './routes/api.v1.documents.$documentId'
import { Route as ApiV1DocumentsGenerateRouteImport } from './routes/api.v1.documents.generate'
import { Route as ApiV1OauthIntrospectRouteImport } from './routes/api.v1.oauth.introspect'
import { Route as ApiV1OauthTokenRouteImport } from './routes/api.v1.oauth.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevelopersRoute = AuthenticatedDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1TemplatesRoute = ApiV1TemplatesRouteImport.update({
  id: '/api/v1/templates',
  path: '/api/v1/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DocumentsDocumentIdRoute =
  ApiV1DocumentsDocumentIdRouteImport.update({
    id: '/api/v1/documents/$documentId',
    path: '/api/v1/documents/$documentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DocumentsGenerateRoute = ApiV1DocumentsGenerateRouteImport.update({
  id: '/api/v1/documents/generate',
  path: '/api/v1/documents/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OauthIntrospectRoute = ApiV1OauthIntrospectRouteImport.update({
  id: '/api/v1/oauth/introspect',
  path: '/api/v1/oauth/introspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OauthTokenRoute = ApiV1OauthTokenRouteImport.update({
  id: '/api/v1/oauth/token',
  path: '/api/v1/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/invite': typeof InviteRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/developers': typeof AuthenticatedDevelopersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/invite': typeof AuthInviteRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/api/v1/templates': typeof ApiV1TemplatesRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/v1/documents/$documentId': typeof ApiV1DocumentsDocumentIdRoute
  '/api/v1/documents/generate': typeof ApiV1DocumentsGenerateRoute
  '/api/v1/oauth/introspect': typeof ApiV1OauthIntrospectRoute
  '/api/v1/oauth/token': typeof ApiV1OauthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/invite': typeof InviteRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/developers': typeof AuthenticatedDevelopersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/invite': typeof AuthInviteRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/api/v1/templates': typeof ApiV1TemplatesRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/api/v1/documents/$documentId': typeof ApiV1DocumentsDocumentIdRoute
  '/api/v1/documents/generate': typeof ApiV1DocumentsGenerateRoute
  '/api/v1/oauth/introspect': typeof ApiV1OauthIntrospectRoute
  '/api/v1/oauth/token': typeof ApiV1OauthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/invite': typeof InviteRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/developers': typeof AuthenticatedDevelopersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/invite': typeof AuthInviteRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/api/v1/templates': typeof ApiV1TemplatesRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/v1/documents/$documentId': typeof ApiV1DocumentsDocumentIdRoute
  '/api/v1/documents/generate': typeof ApiV1DocumentsGenerateRoute
  '/api/v1/oauth/introspect': typeof ApiV1OauthIntrospectRoute
  '/api/v1/oauth/token': typeof ApiV1OauthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/batches'
    | '/developers'
    | '/settings'
    | '/auth/invite'
    | '/templates/$templateId'
    | '/api/v1/templates'
    | '/api/webhooks/resend'
    | '/templates/'
    | '/api/v1/documents/$documentId'
    | '/api/v1/documents/generate'
    | '/api/v1/oauth/introspect'
    | '/api/v1/oauth/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/batches'
    | '/developers'
    | '/settings'
    | '/auth/invite'
    | '/templates/$templateId'
    | '/api/v1/templates'
    | '/api/webhooks/resend'
    | '/templates'
    | '/api/v1/documents/$documentId'
    | '/api/v1/documents/generate'
    | '/api/v1/oauth/introspect'
    | '/api/v1/oauth/token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invite'
    | '/_authenticated/batches'
    | '/_authenticated/developers'
    | '/_authenticated/settings'
    | '/auth/invite'
    | '/_authenticated/templates/$templateId'
    | '/api/v1/templates'
    | '/api/webhooks/resend'
    | '/_authenticated/templates/'
    | '/api/v1/documents/$documentId'
    | '/api/v1/documents/generate'
    | '/api/v1/oauth/introspect'
    | '/api/v1/oauth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteRoute: typeof InviteRoute
  ApiV1TemplatesRoute: typeof ApiV1TemplatesRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiV1DocumentsDocumentIdRoute: typeof ApiV1DocumentsDocumentIdRoute
  ApiV1DocumentsGenerateRoute: typeof ApiV1DocumentsGenerateRoute
  ApiV1OauthIntrospectRoute: typeof ApiV1OauthIntrospectRoute
  ApiV1OauthTokenRoute: typeof ApiV1OauthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developers': {
      id: '/_authenticated/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof AuthenticatedDevelopersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/templates': {
      id: '/api/v1/templates'
      path: '/api/v1/templates'
      fullPath: '/api/v1/templates'
      preLoaderRoute: typeof ApiV1TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/documents/$documentId': {
      id: '/api/v1/documents/$documentId'
      path: '/api/v1/documents/$documentId'
      fullPath: '/api/v1/documents/$documentId'
      preLoaderRoute: typeof ApiV1DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/documents/generate': {
      id: '/api/v1/documents/generate'
      path: '/api/v1/documents/generate'
      fullPath: '/api/v1/documents/generate'
      preLoaderRoute: typeof ApiV1DocumentsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oauth/introspect': {
      id: '/api/v1/oauth/introspect'
      path: '/api/v1/oauth/introspect'
      fullPath: '/api/v1/oauth/introspect'
      preLoaderRoute: typeof ApiV1OauthIntrospectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oauth/token': {
      id: '/api/v1/oauth/token'
      path: '/api/v1/oauth/token'
      fullPath: '/api/v1/oauth/token'
      preLoaderRoute: typeof ApiV1OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedDevelopersRoute: typeof AuthenticatedDevelopersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedDevelopersRoute: AuthenticatedDevelopersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthInviteRoute: typeof AuthInviteRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthInviteRoute: AuthInviteRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteRoute: InviteRoute,
  ApiV1TemplatesRoute: ApiV1TemplatesRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiV1DocumentsDocumentIdRoute: ApiV1DocumentsDocumentIdRoute,
  ApiV1DocumentsGenerateRoute: ApiV1DocumentsGenerateRoute,
  ApiV1OauthIntrospectRoute: ApiV1OauthIntrospectRoute,
  ApiV1OauthTokenRoute: ApiV1OauthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
